name: ChunkClaim
version: 0.1 Beta
author: tylix
main: me.tylix.chunkclaim.ChunkClaim
commands:
  chunkclaim:
    aliases:
      - cc
      - chunk
  chunkclaimadmin:
    aliases:
      - cca
      - chunka
  back:
  home:
api-version: 1.13