name: ChunkClaim
version: 0.1
author: tylix
main: me.tylix.chunkclaim.ChunkClaim
commands:
  chunkclaim:
    aliases:
      - cc
      - chunk
  chunkclaimadmin:
    aliases:
      - cca
      - chunka
api-version: 1.13